openapi: 3.0.1
info:
  title: Static OpenAPI document of seniorTalents resource
  description: SeniorTalent resources Open API documentation
  version: "1.0"

servers:
  - url: http://localhost:8080/api/swagger-ui
    description: Optional dev mode server description

paths:
  /seniors:
    get:
      responses:
        200:
          description: OK - senior list
          content:
            application/json: {}
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Senior'
      responses:
        200:
          description: new senior resource created
          content:
            application/json: {}
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Senior'
      responses:
        200:
          description: OK - senior resource deleted
          content:
            application/json: {}
components:
  schemas:
    Senior:
      properties:
        email:
          type: string
        password:
          type: string